-- FlowerVN production-like schema for Supabase/PostgreSQL
create extension if not exists pgcrypto;

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_not_blank check (length(trim(name)) >= 2)
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id) on delete set null,
  sku text not null unique,
  name text not null,
  slug text not null unique,
  description text not null default '',
  price numeric(12,2) not null,
  sale_price numeric(12,2),
  image_url text,
  images jsonb not null default '[]'::jsonb,
  stock integer not null default 0,
  reserved_stock integer not null default 0,
  low_stock_threshold integer not null default 5,
  is_active boolean not null default true,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_price_positive check (price >= 0),
  constraint products_sale_price_valid check (sale_price is null or (sale_price >= 0 and sale_price <= price)),
  constraint products_stock_valid check (stock >= 0 and reserved_stock >= 0 and reserved_stock <= stock),
  constraint products_name_not_blank check (length(trim(name)) >= 2)
);

create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null unique,
  phone text not null,
  password_hash text,
  role text not null default 'customer',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customers_role_valid check (role in ('customer','admin')),
  constraint customers_email_valid check (position('@' in email) > 1)
);

create table if not exists coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  description text,
  discount_type text not null,
  discount_value numeric(12,2) not null,
  min_order_amount numeric(12,2) not null default 0,
  max_discount_amount numeric(12,2),
  usage_limit integer,
  used_count integer not null default 0,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  is_active boolean not null default true,
  constraint coupons_type_valid check (discount_type in ('percent','fixed')),
  constraint coupons_value_valid check (discount_value > 0),
  constraint coupons_usage_valid check (usage_limit is null or (usage_limit >= 0 and used_count <= usage_limit)),
  constraint coupons_dates_valid check (expires_at is null or expires_at > starts_at)
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique default ('FLW-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,10))),
  customer_id uuid references customers(id) on delete set null,
  receiver_name text not null,
  receiver_phone text not null,
  delivery_address text not null,
  delivery_date date,
  note text,
  payment_method text not null default 'cod',
  payment_status text not null default 'unpaid',
  status text not null default 'pending',
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  discount_amount numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  coupon_code text,
  idempotency_key text unique,
  cancelled_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_status_valid check (status in ('pending','confirmed','preparing','shipping','delivered','cancelled','returned')),
  constraint orders_payment_method_valid check (payment_method in ('cod','bank_transfer','online')),
  constraint orders_payment_status_valid check (payment_status in ('unpaid','paid','failed','refunded')),
  constraint orders_amounts_valid check (subtotal >= 0 and delivery_fee >= 0 and discount_amount >= 0 and total_amount >= 0),
  constraint orders_contact_valid check (length(trim(receiver_name)) >= 2 and length(trim(receiver_phone)) >= 8 and length(trim(delivery_address)) >= 8)
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  product_name text not null,
  sku text not null,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  subtotal numeric(12,2) not null,
  created_at timestamptz not null default now(),
  constraint order_items_quantity_valid check (quantity between 1 and 99),
  constraint order_items_amount_valid check (unit_price >= 0 and subtotal >= 0)
);

create table if not exists order_status_history (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  old_status text,
  new_status text not null,
  changed_by uuid references customers(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  customer_id uuid references customers(id) on delete set null,
  rating integer not null,
  title text,
  content text,
  is_approved boolean not null default false,
  created_at timestamptz not null default now(),
  constraint reviews_rating_valid check (rating between 1 and 5),
  unique(product_id, customer_id)
);

create index if not exists products_category_idx on products(category_id);
create index if not exists products_active_idx on products(is_active, deleted_at);
create index if not exists products_price_idx on products(price);
create index if not exists orders_status_idx on orders(status, created_at desc);
create index if not exists orders_customer_idx on orders(customer_id, created_at desc);
create index if not exists order_items_order_idx on order_items(order_id);
create index if not exists reviews_product_idx on reviews(product_id, is_approved);

-- Atomic order creation: locks product rows, validates stock, reserves stock and inserts order/items.
create or replace function create_order_atomic(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id bigint;
  v_subtotal numeric(12,2) := 0;
  v_delivery_fee numeric(12,2) := 0;
  v_discount numeric(12,2) := 0;
  v_total numeric(12,2) := 0;
  v_item jsonb;
  v_product products%rowtype;
  v_qty integer;
  v_unit numeric(12,2);
  v_code text;
  v_coupon coupons%rowtype;
begin
  if coalesce(jsonb_array_length(payload->'items'), 0) = 0 then
    raise exception using errcode = 'P0001', message = 'EMPTY_ORDER_ITEMS';
  end if;
  if nullif(trim(payload->>'receiver_name'),'') is null or nullif(trim(payload->>'receiver_phone'),'') is null or nullif(trim(payload->>'delivery_address'),'') is null then
    raise exception using errcode = 'P0001', message = 'INVALID_RECEIVER_INFORMATION';
  end if;

  if nullif(payload->>'idempotency_key','') is not null then
    select id into v_order_id from orders where idempotency_key = payload->>'idempotency_key';
    if v_order_id is not null then
      return jsonb_build_object('id', v_order_id, 'duplicate', true);
    end if;
  end if;

  for v_item in select * from jsonb_array_elements(payload->'items') loop
    v_qty := (v_item->>'quantity')::integer;
    select * into v_product from products where id = (v_item->>'product_id')::bigint and is_active = true and deleted_at is null for update;
    if not found then raise exception using errcode = 'P0001', message = 'PRODUCT_NOT_FOUND'; end if;
    if v_qty is null or v_qty < 1 or v_qty > 99 then raise exception using errcode = 'P0001', message = 'INVALID_QUANTITY'; end if;
    if (v_product.stock - v_product.reserved_stock) < v_qty then raise exception using errcode = 'P0001', message = 'INSUFFICIENT_STOCK:' || v_product.name; end if;
    v_unit := coalesce(v_product.sale_price, v_product.price);
    v_subtotal := v_subtotal + (v_unit * v_qty);
  end loop;

  v_delivery_fee := case when v_subtotal >= 500000 then 0 else 30000 end;
  v_code := upper(nullif(trim(payload->>'coupon_code'),''));
  if v_code is not null then
    select * into v_coupon from coupons where code = v_code and is_active = true and starts_at <= now() and (expires_at is null or expires_at >= now()) for update;
    if found and (v_coupon.usage_limit is null or v_coupon.used_count < v_coupon.usage_limit) and v_subtotal >= v_coupon.min_order_amount then
      v_discount := case when v_coupon.discount_type = 'percent' then least(v_subtotal * v_coupon.discount_value / 100, coalesce(v_coupon.max_discount_amount, v_subtotal)) else least(v_coupon.discount_value, v_subtotal) end;
      update coupons set used_count = used_count + 1 where id = v_coupon.id;
    end if;
  end if;
  v_total := greatest(0, v_subtotal + v_delivery_fee - v_discount);

  insert into orders(customer_id, receiver_name, receiver_phone, delivery_address, delivery_date, note, payment_method, subtotal, delivery_fee, discount_amount, total_amount, coupon_code, idempotency_key)
  values ((payload->>'customer_id')::uuid, trim(payload->>'receiver_name'), trim(payload->>'receiver_phone'), trim(payload->>'delivery_address'), nullif(payload->>'delivery_date','')::date, payload->>'note', coalesce(payload->>'payment_method','cod'), v_subtotal, v_delivery_fee, v_discount, v_total, v_code, nullif(payload->>'idempotency_key','')) returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(payload->'items') loop
    select * into v_product from products where id = (v_item->>'product_id')::bigint for update;
    v_qty := (v_item->>'quantity')::integer;
    v_unit := coalesce(v_product.sale_price, v_product.price);
    insert into order_items(order_id, product_id, product_name, sku, quantity, unit_price, subtotal)
    values (v_order_id, v_product.id, v_product.name, v_product.sku, v_qty, v_unit, v_unit * v_qty);
    update products set reserved_stock = reserved_stock + v_qty, updated_at = now() where id = v_product.id;
  end loop;
  insert into order_status_history(order_id, new_status, note) values (v_order_id, 'pending', 'Order created');
  return jsonb_build_object('id', v_order_id, 'total_amount', v_total, 'delivery_fee', v_delivery_fee, 'discount_amount', v_discount, 'duplicate', false);
end;
$$;
